name: echi_recipe
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - cython
  - hydra-core
  - hydra-submitit-launcher
  - librosa
  - matplotlib
  - numpy==1.26.4
  - omegaconf
  - onnxruntime
  - pip
  - pysoundfile
  - pytorch
  - pytorch-cuda
  - torchaudio
  - torchmetrics
  - tqdm
  - wandb
  - pip:
      - auraloss
      - pysptk --prefer-binary
      - sentencepiece
      - torch-stoi
