# Path to where the submitted data is stored
submission: ???

output_file: ${..paths.scratch}/results.{device}.json

segment_dir: ${..paths.scratch}/segments/{device}

csv_dir: ${..paths.echi}/metadata/ref/dev # Path to the CSV files for evaluation
ref_segment_dir: ${..paths.ref_segment_dir} # Path to the reference segment directory

score_config: config/metrics.yaml
use_gpu: false
decimate_factor: 1 # Decimation factor for the evaluation

