# Path to where the submitted data is stored
enhanced_dir: ${..paths.enhanced_dir}

results_file: ${..paths.results_file}

segment_dir: ${..paths.scratch}/segments/{device}

csv_dir: ${..paths.echi}/metadata/ref/dev # Path to the CSV files for evaluation
ref_segment_dir: ${..paths.ref_segment_dir} # Path to the reference segment directory

#score_config: config/metrics.yaml
score_config: config/metrics_test.yaml
use_gpu: false
batch: (1, 1) #  (i, N), batch i of N; note (1, 1) means no batching

dataset: ${..shared.dataset}
devices: ${..shared.devices}

sessions_file: ${..paths.sessions_file}
