defaults:
  - _self_
  - paths: default

# Path to where the submitted data is stored
submission: ???

output_file: ${paths.scratch}/results.json

reference: ${paths.scratch}/reference # Path to the ground truth files
enhanced: ${paths.scratch}/enhanced # Path to the generated files
score_config: config/metrics.yaml
use_gpu: false

hydra:
  run:
    dir: ${paths.scratch}/logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
