# # signal related metrics
# # -- sir: signal to interference ratio
# # -- sar: signal to artifact ratio
# # -- sdr: signal to distortion ratio
# # -- ci-sdr: scale-invariant signal to distortion ratio
# # -- si-snri: scale-invariant signal to noise ratio improvement
# - name: signal_metric
#
# # pesq related metrics
# - name: pesq
#
# # stoi related metrics
# # -- stoi: short-time objective intelligibility
# - name: stoi
#
# # torchaudio-squim
# # -- torch_squim_pesq: reference-less pesq
# # -- torch_squim_stoi: reference-less stoi
# # -- torch_squim_si_sdr: reference-less si-sdr
# # -- torch_squim_mos: MOS score with reference
# - name: squim_ref
# - name: squim_no_ref
#
# - name: pysepm
##### All above here are working

#- name: srmr
#- name: pseudo_mos
#  predictor_types: ["utmos", "dnsmos"]
#  predictor_args:
#    utmos:
#      fs: 16000
#    dnsmos:
#      fs: 16000

- name: nisqa
#  No such file or directory: './tools/NISQA/weights/nisqa.tar'
