root: data # Root directory for all data directories

# Path to the ECHI dataset directory
echi: ${paths.root}/chime9_echi
signal_dir: ${paths.echi}/{device}/{dataset}
echi_signal: ${paths.signal_dir}/{session}.{device}.wav

ref_signal_dir: ${paths.echi}/ref/{dataset}

# Path to the reference segment directory
ref_segment_dir: ${paths.scratch}/ref_segments/{dataset}/{device}

# Submission paths
scratch: ${paths.root}/scratch # Path to scratch space for preprocessing

enhanced_dir: ${paths.scratch}/{dataset}
enhanced_signal: ${paths.enhanced_dir}/{session}.{device}.{pid}.wav
