root: data # Root directory for all data directories
echi: ${paths.root}/chime9_echi # Path to the ECHI dataset directory
scratch: ${paths.root}/scratch # Path to scratch space for preprocessing

ref_segment_dir: ${paths.scratch}/ref_segments # Path to the reference segment directory
