# Submitit configuration for running on slurm cluster

# These will need to be editted to match your cluster setup.
# The example below is for the University of Sheffield.

defaults:
  - submitit_slurm

mem_gb: 16
tasks_per_node: 1
timeout_min: 180
additional_parameters:
  account: clarity
  partition: clarity
setup:
  [
    "module load Anaconda3/2019.07",
    "module load libsndfile/1.0.28-GCCcore-9.3.0",
    "source activate echi_recipe",
    "export SLURM_EXPORT_ENV=ALL",
    "export PYTHONPATH=src",
  ]
